import { Blockchain, SandboxContract, TreasuryContract } from '@ton/sandbox';
import { toNano } from '@ton/core';
import { Bounty, Payout, Refund } from '../build/Bounty/tact_Bounty';
import '@ton/test-utils';

describe('Bounty', () => {
    let blockchain: Blockchain;
    let deployer: SandboxContract<TreasuryContract>;
    let bounty: SandboxContract<Bounty>;
    let owner: SandboxContract<TreasuryContract>;
    let oracle: SandboxContract<TreasuryContract>;

    beforeEach(async () => {
        blockchain = await Blockchain.create();
        owner = await blockchain.treasury('owner');
        oracle = await blockchain.treasury('oracle');
        deployer = await blockchain.treasury('deployer');

        bounty = blockchain.openContract(await Bounty.fromInit(owner.address, oracle.address));

        const deployResult = await bounty.send(
            deployer.getSender(),
            {
                value: toNano('0.05'),
            },
            {
                $$type: 'Deploy',
                queryId: 0n,
            }
        );

        expect(deployResult.transactions).toHaveTransaction({
            from: deployer.address,
            to: bounty.address,
            deploy: true,
            success: true,
        });
    });

    it('should deploy', async () => {
        // the check is done inside beforeEach
        // blockchain and bounty are ready to use
    });

    it('should accept funds', async () => {
        const result = await owner.send({
            to: bounty.address,
            value: toNano('10'),
            sendMode: 1, // Pay gas separately
        });

        expect(result.transactions).toHaveTransaction({
            from: owner.address,
            to: bounty.address,
            success: true,
        });

        const balance = await bounty.getBalance();
        // Balance > 10 because of initial deploy funds + deposit
        // Balance > 9.9 (accounting for gas)
        expect(balance).toBeGreaterThan(toNano('9.9'));
    });

    it('should payout when oracle signs', async () => {
        // Fund the bounty first
        await owner.send({
            to: bounty.address,
            value: toNano('10'),
        });

        const developer = await blockchain.treasury('developer');
        const payoutAmount = toNano('9');

        const payoutMsg: Payout = {
            $$type: 'Payout',
            amount: payoutAmount,
            recipient: developer.address,
        };

        const result = await bounty.send(
            oracle.getSender(),
            {
                value: toNano('0.1'), // Gas for the operation
            },
            payoutMsg
        );

        expect(result.transactions).toHaveTransaction({
            from: oracle.address,
            to: bounty.address,
            success: true,
        });

        expect(result.transactions).toHaveTransaction({
            from: bounty.address,
            to: developer.address,
            value: payoutAmount,
            success: true,
        });

        // Attempt Second Payout (Replay Attack)
        const result2 = await bounty.send(
            oracle.getSender(),
            {
                value: toNano('0.1'),
            },
            payoutMsg
        );

        expect(result2.transactions).toHaveTransaction({
            from: oracle.address,
            to: bounty.address,
            success: false, // Should fail
            // exitCode for "Already Paid". Since we don't know the exact ID generated by Tact, just checking failure is enough.
            // But if we wanted to be specific, we'd check the exit code mapped to that string.
        });
    });

    it('should NOT payout if sender is not oracle', async () => {
        await owner.send({
            to: bounty.address,
            value: toNano('10'),
        });

        const developer = await blockchain.treasury('developer');
        const payoutAmount = toNano('9');
        const payoutMsg: Payout = {
            $$type: 'Payout',
            amount: payoutAmount,
            recipient: developer.address,
        };

        // Try to payout as Owner (should fail)
        const result = await bounty.send(
            owner.getSender(),
            {
                value: toNano('0.1'),
            },
            payoutMsg
        );

        expect(result.transactions).toHaveTransaction({
            from: owner.address,
            to: bounty.address,
            success: false, // Should fail require
            // exitCode: 4429, // Don't check specific exit code as it changes with Tact versions
        });
    });
});
