export const providers = [
  {
    id: "1",
    name: "Aino Mäkinen",
    avatar: "https://i.pravatar.cc/150?img=47",
    category: ["cleaning"],
    hourlyRate: 25,
    ratingAvg: 4.9,
    ratingCount: 62,
    responseTime: 0.8,
    bio: "Professional cleaner with 8 years of experience in Helsinki. Specialising in deep cleaning and regular home maintenance. I bring all my own eco-friendly supplies.",
    availableThisWeek: true,
    city: "Helsinki",
    zip: "00100",
    isNew: false,
  },
  {
    id: "2",
    name: "Mikko Leinonen",
    avatar: "https://i.pravatar.cc/150?img=52",
    category: ["cleaning", "handyman"],
    hourlyRate: 28,
    ratingAvg: 4.7,
    ratingCount: 38,
    responseTime: 1.5,
    bio: "Versatile home service professional. I handle everything from deep cleaning to minor repairs and furniture assembly. Available weekdays and Saturdays.",
    availableThisWeek: true,
    city: "Helsinki",
    zip: "00200",
    isNew: false,
  },
  {
    id: "3",
    name: "Liisa Korhonen",
    avatar: "https://i.pravatar.cc/150?img=44",
    category: ["cleaning", "laundry"],
    hourlyRate: 23,
    ratingAvg: 4.8,
    ratingCount: 91,
    responseTime: 0.5,
    bio: "Trusted cleaner in Kallio and Sörnäinen area. I provide thorough, reliable cleaning and full laundry & ironing service. Over 90 five-star reviews speak for themselves!",
    availableThisWeek: true,
    city: "Helsinki",
    zip: "00500",
    isNew: false,
  },
  {
    id: "4",
    name: "Juhani Virtanen",
    avatar: "https://i.pravatar.cc/150?img=57",
    category: ["handyman"],
    hourlyRate: 35,
    ratingAvg: 4.6,
    ratingCount: 24,
    responseTime: 2.1,
    bio: "Licensed handyman with 15 years of experience. Specialise in plumbing, electrical basics, carpentry, and general home repairs. Fully insured.",
    availableThisWeek: false,
    city: "Espoo",
    zip: "02100",
    isNew: false,
  },
  {
    id: "5",
    name: "Sari Nieminen",
    avatar: "https://i.pravatar.cc/150?img=41",
    category: ["cleaning"],
    hourlyRate: 24,
    ratingAvg: 0,
    ratingCount: 0,
    responseTime: 1.0,
    bio: "New to SabarKoti but highly experienced! 5 years cleaning homes across Espoo and Vantaa. Fast, reliable, and very detail-oriented.",
    availableThisWeek: true,
    city: "Espoo",
    zip: "02600",
    isNew: true,
  },
];

export const reviews = [
  { providerId: "1", reviewer: "Anna K.", rating: 5, comment: "Aino was absolutely fantastic — the apartment looked brand new. Will definitely rebook every week!", date: "Jan 28, 2026" },
  { providerId: "1", reviewer: "Petri M.", rating: 5, comment: "Very professional, arrived on time and did an outstanding job. Highly recommended.", date: "Jan 12, 2026" },
  { providerId: "1", reviewer: "Tiina L.", rating: 4, comment: "Great cleaning, very thorough. Communication was smooth and the tax receipt arrived immediately after.", date: "Dec 18, 2025" },
  { providerId: "2", reviewer: "Jari P.", rating: 5, comment: "Mikko fixed two things and cleaned the whole flat. Incredibly efficient — saved me a ton of time.", date: "Feb 3, 2026" },
  { providerId: "2", reviewer: "Maria S.", rating: 4, comment: "Good work overall, minor things missed but Mikko came back to fix them with no fuss.", date: "Jan 21, 2026" },
  { providerId: "3", reviewer: "Outi R.", rating: 5, comment: "Liisa is the best — 3rd time booking and every time is perfect. The kotitalousvähennys saving alone is worth it!", date: "Feb 10, 2026" },
  { providerId: "3", reviewer: "Harri V.", rating: 5, comment: "Excellent service. Laundry and ironing done to a high standard. Clothes looked better than from dry cleaning.", date: "Feb 1, 2026" },
];

export const customerBookings = [
  {
    id: "b1",
    providerId: "1",
    providerName: "Aino Mäkinen",
    providerAvatar: "https://i.pravatar.cc/150?img=47",
    category: "Cleaning",
    date: "Mon 24 Feb 2026",
    time: "09:00–12:00",
    address: "Mannerheimintie 10, Helsinki",
    status: "confirmed",
    laborCost: 75,
    totalCharged: 75,
    taxDeduction: 33.75,
    effectiveCost: 41.25,
    hasReview: false,
    hasReceipt: false,
  },
  {
    id: "b2",
    providerId: "3",
    providerName: "Liisa Korhonen",
    providerAvatar: "https://i.pravatar.cc/150?img=44",
    category: "Cleaning + Laundry",
    date: "Wed 5 Feb 2026",
    time: "10:00–14:00",
    address: "Hämeentie 45, Helsinki",
    status: "completed",
    laborCost: 92,
    totalCharged: 92,
    taxDeduction: 41.4,
    effectiveCost: 50.6,
    hasReview: true,
    hasReceipt: true,
  },
  {
    id: "b3",
    providerId: "2",
    providerName: "Mikko Leinonen",
    providerAvatar: "https://i.pravatar.cc/150?img=52",
    category: "Handyman",
    date: "Mon 20 Jan 2026",
    time: "13:00–15:00",
    address: "Fredrikinkatu 22, Helsinki",
    status: "completed",
    laborCost: 56,
    totalCharged: 56,
    taxDeduction: 25.2,
    effectiveCost: 30.8,
    hasReview: true,
    hasReceipt: true,
  },
];

export const providerBookings = [
  {
    id: "pb1",
    customerName: "Anna K.",
    customerInitials: "AK",
    area: "Kallio, Helsinki",
    date: "Mon 24 Feb 2026",
    time: "14:00–16:00",
    duration: 2,
    category: "Cleaning",
    status: "pending",
    grossEarning: 50,
    netEarning: 40,
    hoursLeft: 1,
    minutesLeft: 42,
  },
  {
    id: "pb2",
    customerName: "Petri M.",
    customerInitials: "PM",
    area: "Töölö, Helsinki",
    date: "Tue 25 Feb 2026",
    time: "09:00–12:00",
    duration: 3,
    category: "Cleaning",
    status: "confirmed",
    grossEarning: 75,
    netEarning: 60,
    hoursLeft: null,
    minutesLeft: null,
  },
  {
    id: "pb3",
    customerName: "Sanna R.",
    customerInitials: "SR",
    area: "Punavuori, Helsinki",
    date: "Mon 10 Feb 2026",
    time: "10:00–12:00",
    duration: 2,
    category: "Cleaning",
    status: "completed",
    grossEarning: 50,
    netEarning: 40,
    hoursLeft: null,
    minutesLeft: null,
  },
];

export const availabilityData: Record<string, ("available" | "booked" | "unavailable")[]> = {
  "Mon 24 Feb": ["available", "available", "booked", "booked", "available", "unavailable"],
  "Tue 25 Feb": ["unavailable", "unavailable", "available", "available", "available", "available"],
  "Wed 26 Feb": ["available", "available", "available", "unavailable", "unavailable", "unavailable"],
  "Thu 27 Feb": ["available", "available", "available", "available", "available", "available"],
  "Fri 28 Feb": ["unavailable", "unavailable", "available", "available", "unavailable", "unavailable"],
  "Sat 1 Mar":  ["available", "available", "unavailable", "unavailable", "unavailable", "unavailable"],
  "Sun 2 Mar":  ["unavailable", "unavailable", "unavailable", "unavailable", "unavailable", "unavailable"],
};

export const timeSlots = ["09:00–11:00", "11:00–13:00", "13:00–15:00", "15:00–17:00", "17:00–19:00", "19:00–21:00"];

export const earningsData = {
  thisWeekGross: 125,
  thisWeekNet: 100,
  lastWeekGross: 200,
  lastWeekNet: 160,
  totalAllTime: 2340,
  totalNetAllTime: 1872,
  payoutSchedule: "Every Monday",
  nextPayout: "Mon 24 Feb 2026",
  nextPayoutAmount: 100,
  recentPayouts: [
    { date: "Mon 17 Feb", amount: 160, status: "paid" },
    { date: "Mon 10 Feb", amount: 120, status: "paid" },
    { date: "Mon 3 Feb",  amount: 200, status: "paid" },
  ],
};
